channels:
  - defaults
dependencies:
  - numpy-base=1.15.1
  - cython=0.28
  - ipython=6.1.0
  - ipython_genutils=0.2
  - jupyter=1.0.0
  - nbconvert=5.2
  - nbformat=4.4
  - notebook=5.2
  - numpy=1.13
  - pandas=0.20
  - pandocfilters=1.4
  - pip=9.0.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2=py36_intel_0
  - pydaal=2018.0.1.20171012=np113py36_intel_0
  - pygments=2.2.0=py36_intel_1
  - python=3.6.3
  - scikit-learn=0.19.0
  - scipy=0.19.1
  - pip:
    - dvc==0.19.7
    - ml-versioning-tools
    - mlflow==0.7.0
    - nltk==3.3
    - nose==1.3.7
    - pyfasttext==0.4.5
